# Generated by Django 2.0.3 on 2020-03-21 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='email',
            new_name='eemail',
        ),
    ]
